version: "3.8"
services:
  api-gateway:
    container_name: api_gateway_service_container
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4000:4000
    env_file: ./api-gateway/src/configs/.env.development
    environment:
      - DOCKER_ENV=true
      - AUTH_SERVICE_URL=http://auth:4001
      - USER_SERVICE_URL=http://user:4005
      - JOB_SERVICE_URL=http://job:4003
      - CHAT_SERVICE_URL=http://chat:4002
      - NOTIFICATION_SERVICE_URL=http://notification:4004
    volumes:
      - ./api-gateway/src:/app/src # HOT RELOADING
      
    networks:
      - custom-network
  auth:
    container_name: auth_service_container
    build:
      context: ./auth-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4001:4001
    env_file: ./auth-service/src/configs/.env.development
    environment:
      - DOCKER_ENV=true
      - CLIENT_URL=http://localhost:3000
      - USER_SERVICE_URL=http://user:4005
    volumes:
      - ./auth-service/src:/app/src # HOT RELOADING
    networks:
      - custom-network  
  user:
    container_name: user_service_container
    build:
      context: ./user-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4005:4005
    env_file: ./user-service/src/configs/.env.development
    environment:
      - DOCKER_ENV=true
      - NOTIFICATION_SERVICE_URL=http://notification:4004
    volumes:
      - ./user-service/src:/app/src # HOT RELOADING
    networks:
      - custom-network  
  job:
    container_name: job_service_container
    build:
      context: ./job-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4003:4003
    env_file: ./job-service/src/configs/.env.development
    environment:
      - DOCKER_ENV=true
    volumes:
      - ./job-service/src:/app/src # HOT RELOADING 
    networks:
      - custom-network  
  notification:
    container_name: notification_service_container
    build:
      context: ./notification-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4004:4004
    env_file: ./notification-service/src/configs/.env.development
    environment:
      - DOCKER_ENV=true
    volumes:
      - ./notification-service/src:/app/src # HOT RELOADING
    networks:
      - custom-network  
  chat:
    container_name: chat_service_container
    build:
      context: ./chat-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4002:4002
    env_file: ./chat-service/src/configs/.env.development
    environment:
      - DOCKER_ENV=true
      - API_SENDMESSAGE_ENDPOINT=http://api-gateway:4000/v1/messages
      - API_USERS_ENDPOINT=http://user:4005/v1/users
      - API_COMPANY_ENDPOINT=http://job:4003/v1/companies
      - CLIENT_URL=http://localhost:3000
    volumes:
      - ./chat-service/src:/app/src # HOT RELOADING
    networks:
      - custom-network  
networks:
   custom-network:
      external: true  # Use an external, shared network 

